name: Social-Media-Api-CI-Workflow

on: 
   pull_request:
      branches:
        - main
   push:
      branches:
         - main

jobs: 

   test:
       name: 'Run unit tests'
       defaults:
            run:
              working-directory: /
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
          node-version: 20
       - name: Cache Node Modules
         uses: actions/cache@v4
         with:
          path: ~/.npm
          
       - name: 'Install Dependencies'
         run: npm install
         
       - name: 'Start the server'
         run: npm run start

   jest-test: 
          name: 'Jest Test'
          defaults:
            run:
              working-directory: /
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
             node-version: 20
            
          - name: 'Install Dependencies'
            run: npm install

          - name: 'start testing'
            run: npm run test:ci
            
         
  
